name: Publish the Website to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Deploy to FTP / cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:   ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}

          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            .gitignore
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db
            **/*.log
            **/migration.sql          # ← you probably don't want this on production
            text.txt                  # ← looks like test file
            # add more if needed, e.g.:
            # controllersPanel.yml
            # **/tests/
            # **/cache/